import { Prompt  } from "next/font/google";
import "../globals.css";
import Navbar from "@/componeants/navigation";

const prompt = Prompt({
  subsets: ["thai", "latin"],
  weight: ["300"],
  variable: "--font-prompt",
});

export const metadata = {
  title: "The Miniral",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${prompt.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
     <Navbar/>
        {children}
      </body>
    </html>
  );
}
